plugins {
    id 'java'
}

group = 'cn.xiaozhou233.juiceremapper'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/org.projectlombok/lombok
    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor "org.projectlombok:lombok:1.18.42"

}
